# Generated by Django 3.1.3 on 2020-11-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='tags',
            field=models.JSONField(default=list),
        ),
    ]
