# Generated by Django 3.1.3 on 2020-11-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20201105_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='mods',
            field=models.JSONField(default=dict),
        ),
    ]
