# Generated by Django 3.1.3 on 2020-11-06 20:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0003_auto_20201105_1139'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together={('photo', 'user')},
        ),
    ]
